### ISSUE TITLE
How to debug within Eclipse project and Simulator

### ISSUE THREAD

**Issue by bartonhammond** [pedlarstudios/WordOfTheDay#1]
First, thanks for making this project available.  I'm learning a lot from it.  

When I import the project to Eclipse, I am not able to run the debugger.  When I try to create a Debug Configuration, the list of projects doesn't include this one, see image.

I have other projects that I can debug successfully so I think my development environment is setup properly.

I notice that the projects I can debug, show a little icon in the Project Explorer w/ "IQ".  But this project doesn't have that same icon as shown below also

<img width="924" alt="Screen Shot 2020-03-31 at 8 10 36 AM" src="https://user-images.githubusercontent.com/1282364/78030061-25019180-7327-11ea-8e4f-4e78da611b19.png">

**Comment by bhawker** [comment]
Hello there,

It's interesting to me, I _do_ in fact see the IQ icon in Project Explorer for WordOfTheDay. When I attempt to debug however, I get the following error:

`Failed to connect to the simulator.`

I have numerous Connect IQ widget and app projects, and when I attempted to debug several of them, I was able to successfully launch all of the debug configurations for the _app_ type projects I tried, but none of the _widget_ projects (I received the above error on all of them). So in short, I'm not really sure what is going on.

**Comment by bartonhammond** [comment]
What I found was to kill Eclipse every time I started.  Not sure what isn’t
getting cleared out but this seemed to work consistently.

**Comment by bhawker** [comment]
Interesting, so you kill Eclipse every time _after_ you start to debug the application?

**Comment by bartonhammond** [comment]
I can not do 2 debug sessions in a row.  When I finish debugging I make
code changes and the restart eclipse. And I have to kill the simulator too.
